### ISSUE TITLE
Product dynamics data

### ISSUE THREAD

**Issue by erickcernarequejo** [erickcernarequejo/Carrito-Compras-JavaScript#3]
Read product data from json file or database

**Comment by Bivas-Biswas** [comment]
Can You give more details about it ?

**Comment by erickcernarequejo** [comment]
> Can You give more details about it ?

The products together with their prices were statically placed in the index.html file, it would be nice if the products and their values ​​are read from a Json file or from a backend to make it easier to add more.

**Comment by Bivas-Biswas** [comment]
Ok, got it. Can you create JSON data ? so I can work on the dynamic logic.

**Comment by erickcernarequejo** [comment]
> Ok, got it. Can you create JSON data ? so I can work on the dynamic logic.

Sorry, but now I have no time to do it, you would have to create the Json yourself

**Comment by Bivas-Biswas** [comment]
Ok, Cool. Assign me .

**Comment by erickcernarequejo** [comment]
> Ok, Cool. Assign me .

Ok, I assigned you the issue

**Comment by Bivas-Biswas** [comment]
done in my side 🙂

**Comment by erickcernarequejo** [comment]
> done in my side 🙂

Great job, but please also add alt attribute to read from json file and with that I accept the PR

**Comment by erickcernarequejo** [comment]
> done in my side 🙂

Great job, but please also add alt attribute to images and with that I accept the PR
