### ISSUE TITLE
Add products to the order email

### ISSUE THREAD

**Issue by erikafloreso** [erickcernarequejo/Carrito-Compras-JavaScript#4]
Add the details of the products to the email, for example

![image](https://user-images.githubusercontent.com/91773240/135705228-2d836e03-108a-4754-9ad9-7527c7f494eb.png)

**Comment by ankitgauri26** [comment]
@erickcernarequejo - can i work on it? Please assign this issue to me

**Comment by erickcernarequejo** [comment]
> @erickcernarequejo - can i work on it? Please assign this issue to me

Create a new issue if you want to improve what is indicated to assign you
